// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUpGBbOC1lCX-k7K_R7Wr92pU6KKuAn_o',
    appId: '1:595015425637:web:94b4348c443fa7cbf4b08c',
    messagingSenderId: '595015425637',
    projectId: 'mynotes-app-new-624',
    authDomain: 'mynotes-app-new-624.firebaseapp.com',
    storageBucket: 'mynotes-app-new-624.appspot.com',
    measurementId: 'G-J07LJSZ39S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztMYOg9ByeI_KMlxQD7YPHeN4ocTx5v0',
    appId: '1:595015425637:android:5b9a45e66b3313eef4b08c',
    messagingSenderId: '595015425637',
    projectId: 'mynotes-app-new-624',
    storageBucket: 'mynotes-app-new-624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiibMc-eaX7Vyw2ny9EQ8u8Dp5ChbKuPI',
    appId: '1:595015425637:ios:24761bc0460adb5cf4b08c',
    messagingSenderId: '595015425637',
    projectId: 'mynotes-app-new-624',
    storageBucket: 'mynotes-app-new-624.appspot.com',
    iosClientId: '595015425637-k2pitp4edvug70vc60rtv5ksrc4b09gq.apps.googleusercontent.com',
    iosBundleId: 'com.diaryone.mydiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiibMc-eaX7Vyw2ny9EQ8u8Dp5ChbKuPI',
    appId: '1:595015425637:ios:24761bc0460adb5cf4b08c',
    messagingSenderId: '595015425637',
    projectId: 'mynotes-app-new-624',
    storageBucket: 'mynotes-app-new-624.appspot.com',
    iosClientId: '595015425637-k2pitp4edvug70vc60rtv5ksrc4b09gq.apps.googleusercontent.com',
    iosBundleId: 'com.diaryone.mydiary',
  );
}
